<?php

namespace AppBundle\Repository;

/**
 * centinelaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class centinelaRepository extends \Doctrine\ORM\EntityRepository
{
}
